Repository mpgn/CrackMapExec, pull requests merged in 2023-07, with the labels that each got.

#15 Fix #14 with file paths on windows
  cme/protocols/ldap.py
  cme/protocols/rdp.py
  cme/protocols/smb.py
  cme/protocols/winrm.py
Labels: bug-fix

#20 Fix AES authentication for SMB
  cme/connection.py
  cme/modules/dfscoerce.py
  cme/modules/enum_av.py
  cme/modules/petitpotam.py
  cme/modules/printnightmare.py
  cme/modules/shadowcoerce.py
  cme/protocols/smb.py
  cme/protocols/smb/passpol.py
  cme/protocols/smb/samrfunc.py
  cme/protocols/smb/samruser.py
Labels: enhancement

#29 Revert #26 and fix #28
  cme/connection.py
Labels: bug-fix

#33 ldap module: use paged search
  cme/protocols/ldap.py
Labels: enhancement

#37 LDAP Enumeration and Add Computer Modules
  cme/modules/add_computer.py
  cme/modules/comp_desc.py
  cme/modules/group_members.py
Labels: New Module

#27 Stop crashing with "Too many open files" and fixing the missing logger error
  cme/crackmapexec.py
  cme/protocols/smb.py
  poetry.lock
  pyproject.toml
Labels: bug-fix

#39 Update connection.py to work with proxychains
  cme/connection.py
Labels: bug-fix

#46 Version Bump
  cme/cli.py
  pyproject.toml
Labels: documentation

#43 Fix #41
  cme/cli.py
Labels: bug-fix

#47 Update lsassy_dump.py #42
  cme/modules/lsassy_dump.py
Labels: bug-fix

#48 Fix logic flaw for fix #41
  cme/cli.py
Labels: bug-fix

#49 Fixing #45
  cme/connection.py
Labels: bug-fix

#53 Update smb.py to fix issue #51
  cme/protocols/smb.py
  cme/protocols/smb/atexec.py
  cme/protocols/smb/mmcexec.py
Labels: bug-fix

#36 Update impersonate.py
  cme/modules/impersonate.py
Labels: bug-fix

#59 Add option --no-smb for mssql proto
  cme/protocols/mssql.py
  cme/protocols/mssql/proto_args.py
Labels: bug-fix

#60 Feat: Added flag --no-write-check on smb shares
  cme/protocols/smb.py
  cme/protocols/smb/proto_args.py
Labels: enhancement

#61 New module pi
  cme/modules/pi.py
Labels: enhancement, New Module
