Repository mpgn/CrackMapExec, pull requests merged in 2023-08, with the labels that each got.

#69 fix issue #67
  cme/connection.py
Labels: bug-fix

#74 Fix crash in veeam module when password contains whitespaces #72
  cme/data/veeam_dump_module/veeam_dump_mssql.ps1
  cme/data/veeam_dump_module/veeam_dump_postgresql.ps1
  cme/modules/veeam_dump.py
Labels: bug-fix

#77 Fix ldap checker bug
  cme/modules/ldap-checker.py
Labels: bug-fix

#78 Explicit check as file for argument
  cme/crackmapexec.py
Labels: enhancement

#79 Enhanced the comp-desc module
  cme/modules/find-computer.py
Labels: enhancement

#80 Addition to "audit_mode". Reveal the first X characters of password.
  cme/config.py
  cme/data/cme.conf
Labels: enhancement

#82 Fix configparser issue with missing configs
  cme/config.py
Labels: bug-fix

#83 MSSQL Query Processing [Bug Fix]
  cme/protocols/mssql.py
Labels: bug-fix

#84 Kaspersky for Windows Server
  cme/modules/enum_av.py
  cme/modules/ldap-checker.py
Labels: enhancement

#86 New Av check
  cme/modules/enum_av.py
Labels: enhancement

#87 fix brokenpiperror false positive #73
  cme/protocols/mssql.py
  cme/protocols/smb.py
Labels: bug-fix

#88 Update enum_av.py -- Bitdefender Endpoint
  cme/modules/enum_av.py
Labels: enhancement

#90 Add check to veeam module if av stops execution #85
  cme/modules/veeam_dump.py
Labels: enhancement

#89 [rdp] Add missing port variable & bug fixed
  cme/protocols/rdp.py
Labels: bug-fix

#91 [winrm] Formatting output & add '--codec, --no-smb' args
  cme/protocols/winrm.py
  cme/protocols/winrm/proto_args.py
Labels: enhancement

#93 Add color to "signing" and "SMBv1" smb output #92
  cme/protocols/ldap.py
  cme/protocols/rdp.py
  cme/protocols/smb.py
Labels: enhancement

#96 Add hashcat export for cmedb
  cme/cmedb.py
Labels: enhancement

#95 Change info colors for smbv1 and signing to bold for readability
  cme/config.py
  cme/data/cme.conf
  cme/first_run.py
  cme/protocols/ldap.py
  cme/protocols/rdp.py
  cme/protocols/smb.py
Labels: enhancement, bug-fix

#97 [smb] Bug fix #58: Avoid hanging in command execution.
  cme/protocols/smb.py
  cme/protocols/smb/atexec.py
  cme/protocols/smb/mmcexec.py
  cme/protocols/smb/proto_args.py
  cme/protocols/smb/smbexec.py
  cme/protocols/smb/wmiexec.py
Labels: enhancement, bug-fix

#105 Dpapi fix
  cme/modules/wireless.py
  cme/protocols/smb.py
  cme/protocols/smb/proto_args.py
  poetry.lock
  pyproject.toml
Labels: enhancement, bug-fix

#111 Add logging best practices to example module
  cme/modules/example_module.py
Labels: documentation

#112 [rdp] Avoid hanging
  cme/protocols/rdp.py
  cme/protocols/rdp/proto_args.py
Labels: enhancement, bug-fix

#113 Add audit mode and reveal X pwd chars to RDP protocol
  cme/protocols/rdp.py
Labels: bug-fix

#62 Extract credentials in IIS Application Pool configuration files
  cme/modules/appcmd.py
Labels: New Module

#120 Temporary fix for #108 until oscrypto releases a new version
  poetry.lock
  pyproject.toml
Labels: bug-fix

#118 Update enum_av.py
  cme/modules/enum_av.py
Labels: enhancement

#114 [smb] Move firewall_checker to built-in function & Rewrite RDP module #66 & bugs fix
  cme/connection.py
  cme/modules/get_netconnections.py
  cme/modules/rdp.py
  cme/modules/wcc.py
  cme/protocols/smb.py
  cme/protocols/smb/atexec.py
  cme/protocols/smb/mmcexec.py
  cme/protocols/smb/proto_args.py
  cme/protocols/smb/smbexec.py
  cme/protocols/smb/wmiexec.py
Labels: enhancement, bug-fix

#127 [smb] fix server 2003/win7 login issue
  cme/connection.py
  cme/protocols/smb/atexec.py
Labels: bug-fix

#133 Extract Trust relationships
  cme/modules/trust.py
Labels: New Module

#129 [connection.py] bug fix in funciton 'gethost_addrinfo'
  cme/connection.py
  cme/modules/rdp.py
  cme/protocols/smb.py
  cme/protocols/smb/mmcexec.py
  cme/protocols/smb/wmiexec.py
Labels: bug-fix
